#!/usr/bin/env zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# load custom executable functions
for function in ~/.dotfiles/zsh/functions/*; do
  source $function
done

# Special NVM configuration
export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Android configuration
export ANDROID_HOME=/Users/andreas/Library/Android/sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=/Users/andreas/.cargo/env:$PATH

# chruby homebrew install 
# more info: https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma
source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh

source /opt/homebrew/opt/powerlevel10k/powerlevel10k.zsh-theme

export ZSH="/Users/andreas/.oh-my-zsh"

plugins=(
  aws
  brew
  catimg
  docker
  docker-compose
  emoji-clock
  fast-syntax-highlighting
  git
  git-extras
  github
  gitfast
  history-search-multi-word
  kubectl
  node
  npm
  nvm
  python
  vscode
  zsh-autosuggestions
)

# ssh-agent
#zstyle :omz:plugins:ssh-agent agent-forwarding on

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Init aws_completer
source ~/.dotfiles/zsh/aws_zsh_completer.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/andreas/.google-cloud-sdk/path.zsh.inc' ]; then . '/Users/andreas/.google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/andreas/.google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/andreas/.google-cloud-sdk/completion.zsh.inc'; fi

# fnm
export PATH="/Users/andreas/Library/Application Support/fnm:$PATH"
eval "`fnm env`"

# Created by `pipx` on 2024-11-08 08:22:48
export PATH="$PATH:/Users/andreas/.local/bin"

chruby 3.4.1
